// Программа строит средствами объектов библиотеки AutoCAD элементарный
// чертеж из отрезков и некоторого текста. Этот чертеж сохраняется в файле
// формата DWG. Конкретнее: эта программа запускает AutoCAD 2008, рисует
// два отрезка, одну дугу и два текстовых объекта, сохраняет чертеж в
// файле D:\Чертеж.dwg и завершает работу AutoCAD
// ~ ~ ~ ~ ~ ~ ~ ~ 
// Следует подключить библиотеку объектов AutoCAD. Для этого надо выбрать
// Project | Add Reference — вкладка COM — AutoCAD 2008 Type Library,
// а также AutoCAD/ObjectDBX Common 17.0 Type Library
using System;
// Другие директивы using удалены, поскольку они не используются в данной
// программе
namespace ACADЭлементарныйЧертеж
{
    class Program
    {
        static void Main(string[] args)
        {
            // Создаем экземпляр класса AcadApplication:
            var ACAD1 = new Autodesk.AutoCAD.Interop.AcadApplication();
            // Задаем параметр "по умолчанию" для его дальнейшего
            // использования в соответствующих методах:
            var t = Type.Missing;
            var Документ = ACAD1.Documents.Add(t);
            // Видимость:
            ACAD1.Visible = true;
            // Узловые точки чертежа:
            Double[] T1 = { 10.0, 10, 0 };
            Double[] T2 = { 200.0, 200, 0 };
            Double[] T3 = { 200.0, 10, 0 };
            Double[] T4 = { 15.0, 200, 0 };
            Double[] T5 = { 100.0, 100, 0 };
            // Нарисовать отрезок от точки T1 до точки T2:
            Документ.ModelSpace.AddLine(T1, T2);
            // Вертикальный отрезок от точки T2 до точки T3:
            var ВертикальныйОтрезок =
                             Документ.ModelSpace.AddLine(T2, T3);
            // Построить дугу с центром в точке T5, радиусом 80,
            // от линии, параллельной оси Х длиной 180 градусов:
            var Дуга = Документ.ModelSpace.AddArc(T5, 80, 0, Math.PI);
            // или просто Документ.ModelSpace.AddArc(T5, 80, 0, Math.PI)
            // Горизонтальный текст (с разворотом 0 градусов)
            Документ.ModelSpace.AddText("Горизонтальный", T4, 22);
            // Вертикальный текст с разворотом на 90 градусов = ПИ/2:
            var ВертикТекст = Документ.ModelSpace.
                                     AddText("Вертикальный", T1, 22);
            // Задаем разворот текста на 90 гдадусов:
            ВертикТекст.Rotation = Math.PI / 2;
            // Сохраняем чертеж на диске:
            Документ.SaveAs(@"D:\Чертеж.dwg", t, t);
            ACAD1.Quit();
        }
    }
}
